# Generated by Django 3.2.5 on 2022-01-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220120_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
